{% set name = "django-configurations" %}
{% set version = "2.0" %}
{% set sha256 = "b4a4eb3ed631c2abbeb7008b5cc5d8d04b190df838e7b613731d728f674f3a2f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8

test:
  imports:
    - configurations

about:
  home: https://github.com/jazzband/django-configurations
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A helper for organizing Django project settings by relying on well established programming patterns.  '
  description: |
    django-configurations eases Django project configuration by relying on the composability of Python classes. It extends the notion of Django's module based settings loading with well established object oriented programming patterns.
  doc_url: https://django-configurations.readthedocs.io/en/latest/
  dev_url: https://github.com/jazzband/django-configurations

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
