travis:
  secure:
    BINSTAR_TOKEN: gx+aeg/D2iz1LP5dZxFcB3etjTu6kN4vhXa4M2MKN69FEt1MuDUzvtuISrDquTSlN+yRbp4TM/lGcRPxV6AfuZ2U/23nFbk1lNALYbiYJrB53fGd1CA0uZqIZQy9U7vMf8kj77bYqWgdK8pEOCURzYobGTHdCKcydZ1/H/Z+QSuHYZCzR6CTqN+VntPwTY4IjgCA5Q5B2Y/Jbj7GKQkPZrVl1smnSE1VAj+DW5Z4APBgYYViSgELWtBCNJhyZXI9wdFE+YUsmBay5URkucw97W9gxXr46XhDBl8QVDe/nxOjdf+5pzl8IECRLNci8KulSNqxAMGsCHjrOlE0CxXCLcAYbFMkdJtuZlXDM6dWK5Z+X0szbNVj6qTBCN0nGu0CTppmmPAPCJ4AmKBXmYwn6K7Y4Ww53YhPNuuqAY4b7sfBGT9JWRz96LI+OjrrxVkVpEmbBiO+M/G43ple6dIYP2LNKx1p3VJr+Bc15Al+1SsNFEb+9lv36y8SIZ0L7CpOJD4Tb5K3hfoos2c/L3rJBPdMUzjyVEvHNYSz3CXmfBJjuKLULrFEjb4G9DTMh9SBcPMBcQ1s/2URgy6KvbWolBQSAuzQSskX5zZbZWDai//Ruv3jaHzKYlIKKKy62etnYyvLNb46RfskbxvyBaDKSwKRI0bBOYJ9I/Z1F8Brlg0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
