travis:
  secure:
    BINSTAR_TOKEN: hYpBdjtRCeX8L7BBaDAV3ahdMlXS1ahtEyTsXX4+xPPL+nPt5nNqrHv4sfi40HlB3uuOeddPO3IXyrnDq2Pqsll1HqsYtKQ2xFQMC4e1CxJnAqcfAnCe6LRp77qNm5j+YLtCy0Ujtffo2rbrTshLGZYu424FO54SzZgsPOxBYAhsQ5LK0prwKR9Hv4ewpR7pOayjXYR2lfI3AzScbUCeOlUrLKT+tdKxLmwV+OnAeF08NEB3/GE/SbeDUKHdAoL+Y1TymGjJAs3nLSrk1eVtP41UzC6FQv0ZoO9uJNoFAMl6IAyikHSgVaV1Eq5wu/EAuvXP+0p0SQSJoi629Bq/IhPt0ZNL3D9jlNGheOreqiNkRmDdfGlslSEk143JLjQLZa6z5RRKHDENjRYlETnqtvpBTv+6UuWFw8WG0VjiUFNE4SXWKqFwDgQzGytnU/68EW3aUHWGfOo/9WdKijxBN0nqfoY201XVB1YnpvURfT8AQRiZ9YPoVAQhMuLI523xElo4g23vHJjD6e5kKE9ey8vHbJZ5QrXqdp2k3ruL4IRaYYlQodZCofeoIGNpLmTYecsiJdkG/W4k4B6/xXMWh7KRaYEKbrR/oi9nzkjpXN3D4Vz1hE8nWQQBhqju0q4ovk4DxnytcwYPJilBqkQAcoTx0fdzhvIuK6i8GVPnKr0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
